name: golang/static
on: pull_request

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: EI vet
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: vet
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Mock client vet
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: vet
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: integration/mock-client

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: EI check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Mock client check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: integration/mock-client

  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: EI check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Mock client check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: integration/mock-client
